santum_api = "https://tpg.sanctum.so/v1/mainnet?apiKey=<api key here>"
devnet_endpoint = "https://devnet.helius-rpc.com/?api-key=<api key here>"
mainnet_endpoint = "https://mainnet.helius-rpc.com/?api-key=<api key here>"

[payment_details]
resource_server = "HboHBxyjJh4jvrb2XkusMHqZ7rnHNMuVmca8XDN2doS" # You can change this to an address you controll to receive payments
#facilitator = 
client_is_facilitator = true
